//! Full paired translation of _analyse_plane and wave classification.
//!
//! Ported from:
//!   plane_analysis.py — _analyse_plane orchestration
//!   wave_classification.py — time_to_region_label, unify_wave_type,
//!       build_aggregator_input, find_true_peak, _choose_r_cluster,
//!       generate_subwave_name, aggregate_waves_by_type, st_measure
//!   preprocessing.py — convert_angles_to_degrees
//!
//! Constants are generated from ``qpsi/constants.py`` at build time —
//! see ``build.rs`` and ``qpsi/dump_constants_json.py``.

use numpy::PyReadonlyArray1;
use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList};
use rayon::prelude::*;

use crate::gauss::{sum_gaussians_2d_kernel, sum_gaussians_1d_kernel, nearest_idx};
use crate::solver::solve_lm;

// ---------------------------------------------------------------------------
// Constants — generated by build.rs from qpsi/constants.py.
// Registry: qpsi/dump_constants_json.py::EXPORTED.
// ---------------------------------------------------------------------------
include!(concat!(env!("OUT_DIR"), "/constants.rs"));

// ---------------------------------------------------------------------------
// 1) time_to_region_label (wave_classification.py:64-86)
// ---------------------------------------------------------------------------
fn time_to_region_label(t_ecg: f64, rr_ms: f64, offset_ms: f64) -> &'static str {
    if t_ecg >= -offset_ms {
        let frac = t_ecg / rr_ms;
        if t_ecg < QRS_FRAC_MS { return "QRS"; }
        if frac < ST_FRAC { return "ST"; }
        if frac < T_EARLY_FRAC { return "Early-T"; }
        if frac < T_NORMAL_FRAC { return "Normal-T"; }
        "Late-T"
    } else {
        if t_ecg < EARLY_P_MS { return "Early-P"; }
        if t_ecg < NORMAL_P_MS { return "Normal-P"; }
        "Late-P"
    }
}

// ---------------------------------------------------------------------------
// 2) unify_wave_type (wave_classification.py:89-105)
// ---------------------------------------------------------------------------
fn unify_wave_type(raw: &str) -> String {
    let name = raw.to_lowercase();
    let stripped = if name.starts_with("early-") { &name[6..] }
        else if name.starts_with("normal-") { &name[7..] }
        else if name.starts_with("late-") { &name[5..] }
        else { &name };
    if stripped.starts_with('p') { "P".to_string() }
    else if stripped.starts_with('t') { "T".to_string() }
    else if stripped.starts_with("qrs") { "QRS".to_string() }
    else { raw.to_string() }
}

// ---------------------------------------------------------------------------
// 3) find_true_peak (wave_classification.py:112-154)
// ---------------------------------------------------------------------------
fn find_true_peak(
    t_ms: &[f64], vx: &[f64], vy: &[f64],
    t0: f64, sigma0: f64, angle_window_deg: f64,
) -> (f64, f64, f64) {
    let n = t_ms.len();
    let idx0 = nearest_idx(t_ms, t0);

    let dt_ms = if n > 1 { t_ms[1] - t_ms[0] } else { 1.0 };
    let angle_ctr = vy[idx0].atan2(vx[idx0]);
    let win_rad = (2.0 * sigma0 / dt_ms).round().max(1.0) as usize;
    let lo = idx0.saturating_sub(win_rad);
    let hi = (idx0 + win_rad).min(n - 1);

    let angle_window_rad = angle_window_deg.to_radians();
    let mut best_idx = idx0;
    let mut best_mag = 0.0f64;
    let mut found_any = false;

    for i in lo..=hi {
        let ang_i = vy[i].atan2(vx[i]);
        // angle_diff = |angle(exp(j*(ang_i - angle_ctr)))|
        let diff = (ang_i - angle_ctr).sin().atan2((ang_i - angle_ctr).cos()).abs();
        if diff <= angle_window_rad {
            let mag = (vx[i] * vx[i] + vy[i] * vy[i]).sqrt();
            if mag > best_mag || !found_any {
                best_mag = mag;
                best_idx = i;
                found_any = true;
            }
        }
    }

    let amp_peak = (vx[best_idx] * vx[best_idx] + vy[best_idx] * vy[best_idx]).sqrt();
    let angle_peak = vy[best_idx].atan2(vx[best_idx]);
    (t_ms[best_idx], amp_peak, angle_peak)
}

// ---------------------------------------------------------------------------
// 4) _choose_r_cluster (wave_classification.py:161-182)
// ---------------------------------------------------------------------------
fn choose_r_cluster(peak_amps: &[f64], peak_angles: &[f64]) -> usize {
    let ang_lo = (-20.0f64).to_radians();
    let ang_hi = 90.0f64.to_radians();
    let cands: Vec<usize> = peak_angles.iter().enumerate()
        .filter(|(_, &a)| a >= ang_lo && a <= ang_hi)
        .map(|(i, _)| i)
        .collect();
    if !cands.is_empty() {
        *cands.iter().max_by(|&&a, &&b| peak_amps[a].partial_cmp(&peak_amps[b]).unwrap()).unwrap()
    } else {
        peak_amps.iter().enumerate()
            .max_by(|(_, a), (_, b)| a.partial_cmp(b).unwrap())
            .map(|(i, _)| i).unwrap_or(0)
    }
}

// ---------------------------------------------------------------------------
// 5) generate_subwave_name (wave_classification.py:185-223)
// ---------------------------------------------------------------------------
fn generate_subwave_name(
    wtype: &str, idx: usize, n_sub: usize,
    peak_times: &[f64], peak_amps: &[f64], peak_angles: &[f64],
) -> String {
    let wt = wtype.to_uppercase();
    if wt == "QRS" {
        let idx_r = choose_r_cluster(peak_amps, peak_angles);
        if idx == idx_r { return "R".to_string(); }
        if idx < idx_r {
            let q_num = idx_r - idx;
            return if q_num == 1 { "Q".to_string() } else { format!("Q{}", q_num) };
        }
        let s_num = idx - idx_r;
        return if s_num == 1 { "S".to_string() } else { format!("S{}", s_num) };
    }
    if wt == "T" {
        return if idx == 0 { "T".to_string() } else { format!("T{}", idx + 1) };
    }
    if wt == "P" {
        return if idx == n_sub - 1 { "P".to_string() } else { format!("preP{}", n_sub - 1 - idx) };
    }
    format!("{}{}", wt, idx + 1)
}

// ---------------------------------------------------------------------------
// Lump structure for wave aggregation output
// ---------------------------------------------------------------------------
#[derive(Clone, Debug)]
struct Lump {
    wave_type: String,
    start_time: f64,
    peak_time: f64,
    end_time: f64,
    amplitude_mv: f64,
    angle_rad: f64,
    angle_deg: f64,
    center_ms: f64,
    sigma_ms: f64,
}

// ---------------------------------------------------------------------------
// 6) build_aggregator_input (wave_classification.py:230-284)
// ---------------------------------------------------------------------------
fn build_aggregator_input(
    params: &[f64], offset_ms: f64, rr_ms: f64, amplitude_threshold: f64,
) -> std::collections::HashMap<String, Vec<(f64, f64, f64, f64)>> {
    let mut wave_dict: std::collections::HashMap<String, Vec<(f64, f64, f64, f64)>> = std::collections::HashMap::new();
    let n_gauss = params.len() / 4;

    for i in 0..n_gauss {
        let (t0, s, a, ang) = (params[4*i], params[4*i+1], params[4*i+2], params[4*i+3]);
        if a <= amplitude_threshold { continue; }
        let region = time_to_region_label(t0, rr_ms, offset_ms);
        let w_class = unify_wave_type(region);
        wave_dict.entry(w_class).or_default().push((t0, s, a, ang));
    }

    // Sort each bucket descending by t0
    for bucket in wave_dict.values_mut() {
        bucket.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap());
    }

    // T-wave postprocessing: relabel last to "I" if separated + divergent angle
    if let Some(t_list) = wave_dict.get_mut("T") {
        if t_list.len() > 1 {
            let mut sorted = t_list.clone();
            sorted.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap());
            let last = sorted[sorted.len() - 1];
            let prev = sorted[sorted.len() - 2];
            let overlap = (last.0 - prev.0).abs() < 1.41 * (last.1 + prev.1);
            let angle_diff = (last.3 - prev.3).abs();
            if !overlap && angle_diff > 1.0 { // delta_rad=1.0
                wave_dict.entry("I".to_string()).or_default().push(last);
                sorted.pop();
                *wave_dict.get_mut("T").unwrap() = sorted;
            }
        }
    }

    // QRS postprocessing: demote first to "ST" if non-overlapping
    if let Some(qrs_list) = wave_dict.get("QRS").cloned() {
        if qrs_list.len() > 1 {
            let (t0_1, s1, _, _) = qrs_list[0];
            let (t0_2, s2, _, _) = qrs_list[1];
            let overlap = (t0_1 - t0_2).abs() < 1.41 * (s1 + s2);
            if !overlap {
                wave_dict.entry("ST".to_string()).or_default().push(qrs_list[0]);
                wave_dict.insert("QRS".to_string(), qrs_list[1..].to_vec());
            }
        }
    }

    wave_dict
}

// ---------------------------------------------------------------------------
// 7) aggregate_waves_by_type (wave_classification.py:291-386)
// ---------------------------------------------------------------------------
fn aggregate_waves_by_type(
    t_ms: &[f64], vx: &[f64], vy: &[f64],
    wave_groups: &std::collections::HashMap<String, Vec<(f64, f64, f64, f64)>>,
    amplitude_threshold: f64,
) -> Vec<Lump> {
    let delta_angle_rad = DEFAULT_DELTA_ANGLE;
    let angle_window_deg = delta_angle_rad.to_degrees();
    let amp_thr = amplitude_threshold.max(0.01);
    let mut aggregated = Vec::new();

    for (wtype, comps) in wave_groups {
        let mut comps: Vec<(f64, f64, f64, f64)> = comps.iter()
            .filter(|c| c.2 >= amp_thr)
            .cloned().collect();
        if comps.is_empty() { continue; }
        comps.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap());

        // Cluster nearby components
        let mut clusters: Vec<Vec<(f64, f64, f64, f64)>> = Vec::new();
        let mut cur = vec![comps[0]];
        for item in comps.iter().skip(1) {
            let (t_i, sigma_i, amp_i, alpha_i) = *item;
            let (t_p, sigma_p, amp_p, alpha_p) = *cur.last().unwrap();
            let ang_ok = (alpha_i - alpha_p).abs() <= delta_angle_rad;
            let time_ok = (t_i - t_p).abs() <= 2.0 * sigma_i + 2.0 * sigma_p;
            let ratio = (amp_i + 1e-9) / (amp_p + 1e-9);
            let amp_ok = if wtype.to_uppercase() == "P" { ratio.ln() <= 3.0f64.ln() }
                else if wtype.to_uppercase() == "T" { ratio.ln() >= 0.33f64.ln() }
                else { true };
            if ang_ok && time_ok && amp_ok { cur.push(*item); }
            else { clusters.push(cur.clone()); cur = vec![*item]; }
        }
        clusters.push(cur);

        // QRS sub-labelling references
        let mut peak_times = Vec::new();
        let mut peak_amps_vec = Vec::new();
        let mut peak_angles_vec = Vec::new();
        if wtype.to_uppercase() == "QRS" {
            for cl in &clusters {
                let best = cl.iter().max_by(|a, b| a.2.partial_cmp(&b.2).unwrap()).unwrap();
                let idx_c = nearest_idx(t_ms, best.0);
                peak_times.push(best.0);
                peak_amps_vec.push(best.2);
                peak_angles_vec.push(vy[idx_c].atan2(vx[idx_c]));
            }
        }

        for (idx_cl, cl) in clusters.iter().enumerate() {
            let best = cl.iter().max_by(|a, b| a.2.partial_cmp(&b.2).unwrap()).unwrap();
            let (t_peak, amp_peak, angle_peak) = find_true_peak(
                t_ms, vx, vy, best.0, best.1, angle_window_deg,
            );
            let name = generate_subwave_name(
                wtype, idx_cl, clusters.len(),
                &peak_times, &peak_amps_vec, &peak_angles_vec,
            );
            let start_time = cl.iter().map(|(t, s, _, _)| t - 2.0 * s).fold(f64::MAX, f64::min);
            let end_time = cl.iter().map(|(t, s, _, _)| t + 2.0 * s).fold(f64::MIN, f64::max);
            let sigma = (end_time - start_time) / 4.0;

            aggregated.push(Lump {
                wave_type: name,
                start_time: (start_time * 1000.0).round() / 1000.0,
                peak_time: (t_peak * 1000.0).round() / 1000.0,
                end_time: (end_time * 1000.0).round() / 1000.0,
                amplitude_mv: (amp_peak * 1000.0).round() / 1000.0,
                angle_rad: (angle_peak * 1000.0).round() / 1000.0,
                angle_deg: (angle_peak.to_degrees() * 1000.0).round() / 1000.0,
                center_ms: t_peak,
                sigma_ms: sigma,
            });
        }
    }
    aggregated
}

// ---------------------------------------------------------------------------
// 8) st_measure (wave_classification.py:393-428)
// ---------------------------------------------------------------------------
fn st_measure(t_ms: &[f64], vx: &[f64], vy: &[f64], lumps: &[Lump]) -> (f64, f64, f64) {
    let s_end = lumps.iter()
        .find(|l| l.wave_type.to_uppercase() == "S")
        .map(|l| l.end_time);
    let r_end = lumps.iter()
        .find(|l| l.wave_type.to_uppercase() == "R")
        .map(|l| l.end_time);
    let s_end = s_end.or(r_end).unwrap_or(0.0);
    let st_time = s_end + 60.0;
    let idx = nearest_idx(t_ms, st_time);
    let amp = (vx[idx] * vx[idx] + vy[idx] * vy[idx]).sqrt();
    let angle_deg = vy[idx].atan2(vx[idx]).to_degrees();
    (st_time, amp, angle_deg)
}

// ---------------------------------------------------------------------------
// 9) Full _analyse_plane for one beat (plane_analysis.py:75-308)
// ---------------------------------------------------------------------------
fn analyse_plane_single(
    seg6: &[f64],  // (6, n_samples) flattened
    t_ms: &[f64],
    n_samples: usize,
    e2: &[[f64; 6]; 2],  // projection matrix
    g_plane: f64,
    not_noisy: bool,
    amplitude_threshold_unscaled: f64,
    rr_ms: f64,
    offset_ms: f64,
    n_extra: usize,
) -> Vec<Lump> {
    // 4) Direction from projection: v2 = (g_plane * E2) @ seg6
    let mut vx = vec![0.0f64; n_samples];
    let mut vy = vec![0.0f64; n_samples];
    for j in 0..n_samples {
        for k in 0..6 {
            let s = seg6[k * n_samples + j];
            vx[j] += g_plane * e2[0][k] * s;
            vy[j] += g_plane * e2[1][k] * s;
        }
    }

    let mags: Vec<f64> = (0..n_samples).map(|i| (vx[i]*vx[i] + vy[i]*vy[i]).sqrt()).collect();
    let mag_max = mags.iter().cloned().fold(0.0f64, f64::max);
    if mag_max < 1e-3 { return Vec::new(); }

    // Spike isolation + amplitude threshold
    let (v2c_x, v2c_y, amp_thr) = if not_noisy {
        // Clean signal: use raw, reuse mag_max
        (vx.clone(), vy.clone(), amplitude_threshold_unscaled * mag_max)
    } else {
        let eps = 1e-6;
        let mut sorted_mags = mags.clone();
        sorted_mags.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let clip_thr = sorted_mags[sorted_mags.len() / 2];
        let mut clipped_max = 0.0f64;
        let cx: Vec<f64> = (0..n_samples).map(|i| {
            let clip_amt = (mags[i] - clip_thr / 2.0).max(0.0);
            vx[i] / (mags[i] + eps) * clip_amt
        }).collect();
        let cy: Vec<f64> = (0..n_samples).map(|i| {
            let clip_amt = (mags[i] - clip_thr / 2.0).max(0.0);
            let uy = vy[i] / (mags[i] + eps) * clip_amt;
            let m = (cx[i]*cx[i] + uy*uy).sqrt();
            if m > clipped_max { clipped_max = m; }
            uy
        }).collect();
        // Recompute clipped max properly
        let cm: f64 = (0..n_samples).map(|i| (cx[i]*cx[i] + cy[i]*cy[i]).sqrt()).fold(0.0f64, f64::max);
        (cx, cy, amplitude_threshold_unscaled * cm)
    };

    // Timing windows
    let lhs_lo = -0.5 * rr_ms + offset_ms;
    let lhs_hi = -offset_ms;
    let _qrs_lo = -offset_ms;
    let _qrs_hi = 120.0;
    let rhs_lo = 90.0;
    let rhs_hi = 0.5 * rr_ms;

    // Pack v2c as flat [x0..xN, y0..yN] for fitting
    let mut v2c_flat: Vec<f64> = Vec::with_capacity(2 * n_samples);
    v2c_flat.extend_from_slice(&v2c_x);
    v2c_flat.extend_from_slice(&v2c_y);

    // Full hybrid Gaussian fitting — entirely in Rust
    use crate::hybrid::{fit_gaussians_hybrid_subrange, subtract_fitted_2d};

    let t_ms = t_ms.to_vec();
    let qrs_lo = -offset_ms;
    let qrs_hi = 120.0;
    let rhs_lo = 90.0;
    let rhs_hi = 0.5 * rr_ms;

    // QRS fitting
    let w_qrs = fit_gaussians_hybrid_subrange(
        &t_ms, &v2c_x, &v2c_y,
        qrs_lo, qrs_hi, QRS_N_WAVES, n_extra, amp_thr,
        QRS_SIGMA_MAX, QRS_ANGLE_LAMBDA, QRS_AMP_LAMBDA,
        false, 0, 0.5, // refine_sigmas=false, n_restarts=0
    );

    // Subtract QRS, fit T on residual
    let (res_x, res_y) = subtract_fitted_2d(&t_ms, &v2c_x, &v2c_y, &w_qrs);
    let w_t = fit_gaussians_hybrid_subrange(
        &t_ms, &res_x, &res_y,
        rhs_lo, rhs_hi, T_N_WAVES, n_extra, amp_thr,
        T_SIGMA_MAX, T_ANGLE_LAMBDA, T_AMP_LAMBDA,
        false, 0, 0.5, // refine_sigmas=false, n_restarts=0
    );

    // P-wave fitting on original signal
    let w_p_raw = fit_gaussians_hybrid_subrange(
        &t_ms, &v2c_x, &v2c_y,
        lhs_lo, lhs_hi, P_N_WAVES, n_extra, amp_thr,
        P_SIGMA_MAX, P_ANGLE_LAMBDA, P_AMP_LAMBDA,
        false, 0, 0.5, // refine_sigmas=false, n_restarts=0
    );

    // P-wave cleanup: only keep within (-rr_ms/2 + offset_ms, -PAD_HEAD_R_MS)
    let mut w_p = Vec::new();
    for i in 0..(w_p_raw.len() / 4) {
        let t0_p = w_p_raw[4 * i];
        if t0_p >= (-rr_ms / 2.0 + offset_ms) && t0_p <= (-PAD_HEAD_R_MS) {
            w_p.extend_from_slice(&w_p_raw[4*i..4*i+4]);
        }
    }

    // Concatenate all params
    let mut params = Vec::new();
    params.extend_from_slice(&w_t);
    params.extend_from_slice(&w_qrs);
    params.extend(&w_p);

    // P1: Pacing spike detection — paired from plane_analysis.py:224-239
    // Check fitted Gaussians for narrow sigma + large amplitude in P-wave window
    let mut pacing_detected = false;
    let n_gauss = params.len() / 4;
    for i in 0..n_gauss {
        let t0_i = params[4 * i];
        let sigma_i = params[4 * i + 1];
        let amp_i = params[4 * i + 2].abs();
        // Pacing window: [-250, -50] ms, narrow sigma, large amplitude
        if t0_i >= -250.0 && t0_i <= -50.0
            && sigma_i <= PACE_SIGMA_MS
            && amp_i >= PACE_AMP_MV
        {
            pacing_detected = true;
            break;
        }
    }

    // Wave classification
    let mut lumps = {
        let wave_groups = build_aggregator_input(&params, offset_ms, rr_ms, amp_thr);
        aggregate_waves_by_type(&t_ms, &v2c_x, &v2c_y, &wave_groups, amp_thr)
    };
    // Attach pacing flag to the lump list (Python side reads it)
    if pacing_detected {
        lumps.push(Lump {
            wave_type: "PACING".into(),
            start_time: 0.0, peak_time: 0.0, end_time: 0.0,
            amplitude_mv: 0.0, angle_rad: 0.0, angle_deg: 0.0,
            center_ms: 0.0, sigma_ms: 0.0,
        });
    }
    lumps
}

// ---------------------------------------------------------------------------
// 10) Batch process all beats in parallel
// ---------------------------------------------------------------------------

/// Process ALL beats for BOTH planes entirely in Rust with rayon parallelism.
///
/// This replaces the entire per-beat loop in pipeline.py step 7.
/// GIL is released once at entry, rayon parallelizes all beats, GIL
/// reacquired only when returning results to Python.
///
/// Input:
///   beats_seg6_flat: (n_beats, 6, n_samples) flattened — raw 6-lead per beat
///   beats_time_ms_flat: (n_beats, n_samples) flattened — time axes per beat
///   n_beats, n_samples: dimensions
///   e2_limb: 2x6 projection matrix for limb plane (flattened)
///   e2_chest: 2x6 projection matrix for chest plane (flattened)
///   g_limb, g_chest: scalar gains per plane
///   not_noisy: noise flag
///   amp_thr_unscaled: amplitude threshold
///   rr_ms_per_beat: RR interval per beat
///   offset_ms: timing offset
///   n_extra: extra Gaussians for hybrid fitter
///
/// Returns list of dicts per beat: [{beat_idx, plane, wave_type, ...}]
#[pyfunction]
pub fn analyse_beats_full_rust<'py>(
    py: Python<'py>,
    beats_seg6_flat: PyReadonlyArray1<'py, f64>,
    beats_time_ms_flat: PyReadonlyArray1<'py, f64>,
    n_beats: usize,
    sample_counts: PyReadonlyArray1<'py, f64>,  // per-beat sample counts
    e2_limb_flat: PyReadonlyArray1<'py, f64>,
    e2_chest_flat: PyReadonlyArray1<'py, f64>,
    g_limb: f64,
    g_chest: f64,
    not_noisy: bool,
    amp_thr_unscaled: f64,
    rr_ms_per_beat: PyReadonlyArray1<'py, f64>,
    offset_ms: f64,
    n_extra: usize,
) -> PyResult<Bound<'py, PyList>> {
    let seg6_all = beats_seg6_flat.as_slice()?.to_vec();
    let time_all = beats_time_ms_flat.as_slice()?.to_vec();
    let rr_all = rr_ms_per_beat.as_slice()?.to_vec();
    let sc = sample_counts.as_slice()?.to_vec();
    let e2l = e2_limb_flat.as_slice()?;
    let e2c = e2_chest_flat.as_slice()?;

    // Build projection matrices
    let e2_limb: [[f64; 6]; 2] = [
        [e2l[0], e2l[1], e2l[2], e2l[3], e2l[4], e2l[5]],
        [e2l[6], e2l[7], e2l[8], e2l[9], e2l[10], e2l[11]],
    ];
    let e2_chest: [[f64; 6]; 2] = [
        [e2c[0], e2c[1], e2c[2], e2c[3], e2c[4], e2c[5]],
        [e2c[6], e2c[7], e2c[8], e2c[9], e2c[10], e2c[11]],
    ];

    // Compute per-beat offsets for variable-length beats
    let mut seg6_offsets = vec![0usize; n_beats + 1];
    let mut time_offsets = vec![0usize; n_beats + 1];
    for i in 0..n_beats {
        let ns = sc[i] as usize;
        seg6_offsets[i + 1] = seg6_offsets[i] + 6 * ns;  // (6, ns) flattened
        time_offsets[i + 1] = time_offsets[i] + ns;
    }

    // Each task: (beat_idx, plane_idx) where plane_idx 0=limb, 1=chest
    let total_tasks = n_beats * 2;

    let results: Vec<(usize, usize, Vec<Lump>)> = (0..total_tasks)
        .into_par_iter()
        .map(|task_idx| {
            let beat_idx = task_idx / 2;
            let plane_idx = task_idx % 2;
            let ns = sc[beat_idx] as usize;

            let seg6 = &seg6_all[seg6_offsets[beat_idx]..seg6_offsets[beat_idx + 1]];
            let t_ms = &time_all[time_offsets[beat_idx]..time_offsets[beat_idx + 1]];
            let rr_ms = rr_all[beat_idx];

            let (e2, g) = if plane_idx == 0 {
                (&e2_limb, g_limb)
            } else {
                (&e2_chest, g_chest)
            };

            let lumps = analyse_plane_single(
                seg6, t_ms, ns, e2, g,
                not_noisy, amp_thr_unscaled, rr_ms, offset_ms, n_extra,
            );

            (beat_idx, plane_idx, lumps)
        })
        .collect();

    // Convert to Python list of dicts
    let py_list = PyList::empty(py);
    for (beat_idx, plane_idx, lumps) in &results {
        let plane_name = if *plane_idx == 0 { "limb" } else { "chest" };
        for lump in lumps {
            let d = PyDict::new(py);
            d.set_item("beat_idx", *beat_idx)?;
            d.set_item("plane", plane_name)?;
            d.set_item("wave_type", lump.wave_type.as_str())?;
            d.set_item("start_time", lump.start_time)?;
            d.set_item("peak_time", lump.peak_time)?;
            d.set_item("end_time", lump.end_time)?;
            d.set_item("amplitude_mV", lump.amplitude_mv)?;
            d.set_item("angle", lump.angle_rad)?;
            d.set_item("angle_degrees", lump.angle_deg)?;
            d.set_item("center_ms", lump.center_ms)?;
            d.set_item("sigma_ms", lump.sigma_ms)?;
            py_list.append(d)?;
        }
    }

    Ok(py_list.into())
}
