//! Build script: generate ``constants.rs`` in OUT_DIR from ``qpsi/constants.py``.
//!
//! H34 / Q-A6-13. Single source of truth lives in ``qpsi/constants.py``;
//! ``qpsi/dump_constants_json.py::EXPORTED`` is the codegen registry. We
//! invoke Python at build time to dump JSON, parse it here, and emit a
//! file of ``pub const FOO: TYPE = VAL;`` lines that ``plane.rs`` consumes
//! via ``include!(concat!(env!("OUT_DIR"), "/constants.rs"))``.

use std::env;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR")
            .expect("CARGO_MANIFEST_DIR not set by Cargo"),
    );
    let qpsi_dir = manifest_dir
        .parent()
        .expect("qpsi_native/ has no parent — expected qpsi/");
    let constants_py = qpsi_dir.join("constants.py");
    let dump_script = qpsi_dir.join("dump_constants_json.py");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let json_path = out_dir.join("constants.json");
    let rs_path = out_dir.join("constants.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", constants_py.display());
    println!("cargo:rerun-if-changed={}", dump_script.display());
    println!("cargo:rerun-if-env-changed=PYTHON");

    let python = env::var("PYTHON").unwrap_or_else(|_| "python".to_string());

    let output = Command::new(&python)
        .arg(&dump_script)
        .arg(&json_path)
        .output()
        .unwrap_or_else(|e| {
            panic!(
                "Failed to invoke '{} {} {}': {}\n\
                 H34 codegen needs Python to read qpsi/constants.py.\n\
                 Set the PYTHON env var if 'python' is not on PATH.",
                python,
                dump_script.display(),
                json_path.display(),
                e,
            )
        });
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        panic!(
            "Python codegen failed (exit {:?}). Command: {} {} {}\nstderr:\n{}",
            output.status.code(),
            python,
            dump_script.display(),
            json_path.display(),
            stderr,
        );
    }

    let json_text = std::fs::read_to_string(&json_path).unwrap_or_else(|e| {
        panic!("Failed to read {}: {}", json_path.display(), e)
    });
    let rs_text = render_constants(&json_text);
    std::fs::write(&rs_path, rs_text).unwrap_or_else(|e| {
        panic!("Failed to write {}: {}", rs_path.display(), e)
    });
}

/// Parse the JSON payload and emit a Rust file of ``pub const`` declarations.
///
/// Schema: ``{NAME: {"value": <num>, "type": "f64"|"i64"|"usize",
/// "source_name": "..."}}``. Names are sorted for deterministic output.
fn render_constants(json_text: &str) -> String {
    let value: serde_json::Value =
        serde_json::from_str(json_text).expect("constants.json is not valid JSON");
    let map = value
        .as_object()
        .expect("constants.json top level must be an object");

    let mut names: Vec<&String> = map.keys().collect();
    names.sort();

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs from qpsi/constants.py.\n");
    out.push_str("// DO NOT EDIT — see qpsi/dump_constants_json.py::EXPORTED.\n\n");

    for name in names {
        let entry = map[name]
            .as_object()
            .expect("entry must be an object");
        let typ = entry["type"]
            .as_str()
            .expect("type must be a string");
        let source = entry["source_name"]
            .as_str()
            .expect("source_name must be a string");
        let value_node = &entry["value"];

        let rust_value = match typ {
            "f64" => {
                let n = value_node
                    .as_f64()
                    .unwrap_or_else(|| panic!("expected f64 for {}", name));
                // Debug formatting on f64 emits a round-trip-safe form.
                let mut s = format!("{:?}", n);
                if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                    s.push_str(".0");
                }
                s
            }
            "i64" => {
                let n = value_node
                    .as_i64()
                    .unwrap_or_else(|| panic!("expected i64 for {}", name));
                n.to_string()
            }
            "usize" => {
                let n = value_node
                    .as_u64()
                    .unwrap_or_else(|| panic!("expected non-negative integer for {}", name));
                n.to_string()
            }
            other => panic!("unknown type {} for {}", other, name),
        };

        out.push_str(&format!(
            "/// `{name}` -- generated from `qpsi.constants.{source}`.\n\
             #[allow(dead_code)]\n\
             pub const {name}: {typ} = {rust_value};\n",
        ));
    }

    out
}
